In [1]:
from gamefitter import *
import pandas as pd
import pickle
population = pickle.load(open('./data/optimization/population_edgeval_1.499.pickle','rb'))
population.sort(key=lambda x: x['error'])

from collections import defaultdict

hypothesis = population[0]
game_settings = {
            "start_populations_matrix": hypothesis['starting_state'],
            "topology": hypothesis['topology'],
            'alpha': hypothesis['alpha'],
            'log_level': "warning",
            'player_labels':hypothesis['player_labels']
        }
game = PolymatrixGame(**game_settings)
print(hypothesis['strategies'])

[array([[1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
        1, 0, 1, 1, 1]]), array([[1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
        0, 0, 1, 1, 0]]), array([[1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
        0, 1, 0, 1, 0]]), array([[1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
        0, 0, 0, 0, 0]]), array([[0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
        1, 1, 1, 0, 0]]), array([[0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
        1, 0, 1, 1, 0]]), array([[1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
        1, 1, 1, 1, 1]]), array([[1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
        0, 0, 0, 1, 0]]), array([[1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
        0, 0, 1, 1, 0]]), array([[1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
        1, 1, 0, 0, 1]])]

In [8]:
results = defaultdict()
for i, p in enumerate(hypothesis['strategies']):
    game.play(p[0])
    game.get_directed_payoffs()
    print(len(game.directed_edge_payoffs))
    d = game.directed_edge_payoffs
    results[i+2008]=[d[key] for key in d]

702
702
702
702
702
702
702
702
702
702


In [13]:
pickle.dump(results, open('./data/cbmg_results_2008-2019.pickle','wb'))

[2.20986831982125,
 2.20986831982125,
 0,
 2.20986831982125,
 0,
 2.20986831982125,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0.27038762746687534,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0.27038762746687534,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 7.533299080396115,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1.5737585138836347,
 0,
 0,
 0,
 0,
 0,
 3.0138384336382553,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 3.0138384336382553,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1.9856692601635468,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0.50837723986631,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0.50837723986631,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0.50837723986631,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,

In [66]:
# look at the game graph

#d = defaultdict()
hypothesis['strategies'][9][0][1]=0

states = {year:None for year in range(2009,2019)}
states[2008] = np.rint(np.sum(game.state, axis=1))
d = {year:None for year in range(2009,2019)}
d['COUNTRY']=hypothesis['player_labels']
d[2008] = [0]*27
for i, s in enumerate(hypothesis['strategies']):
    game.play(s[0])
    states[2009+i] = np.rint(np.sum(game.state, axis=1))
    d[2009+i] = states[2009+i]-states[2008+i]
df_scores = pd.DataFrame(d)
df_scores
    

[array([[1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
        1, 0, 1, 1, 1]]), array([[1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
        0, 0, 1, 1, 0]]), array([[1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
        0, 1, 0, 1, 0]]), array([[1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
        0, 0, 0, 0, 0]]), array([[0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
        1, 1, 1, 0, 0]]), array([[0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
        1, 0, 1, 1, 0]]), array([[1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
        1, 1, 1, 1, 1]]), array([[1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
        0, 0, 0, 1, 0]]), array([[1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
        0, 0, 1, 1, 0]]), array([[1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
        1, 1, 0, 0, 1]])]

2009  2010  2011  2012  2013  2014  2015  2016  2017  2018  \
0    5.0   2.0   6.0   6.0   3.0   3.0   5.0   4.0   0.0   3.0   
1   10.0  18.0  15.0  14.0  12.0   8.0   7.0  12.0   2.0   2.0   
2  -13.0  -8.0 -13.0 -16.0  -7.0   3.0  -9.0 -15.0   0.0  -6.0   
3   -2.0  -1.0  -1.0  -1.0  -3.0  -3.0  -5.0   3.0  -4.0  -1.0   
4    0.0 -19.0  -7.0  -7.0  -8.0  -8.0  -1.0  -6.0  -9.0  -4.0   
5    0.0  -1.0  -4.0  -4.0   0.0  -2.0  -1.0  -4.0  -4.0  -1.0   
6    0.0   2.0   0.0   0.0   2.0   0.0   1.0   1.0   0.0   1.0   
7    2.0  -1.0   0.0   0.0   0.0   0.0   0.0   0.0  -1.0   2.0   
8    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
9    0.0   1.0   1.0   2.0   0.0   1.0   0.0   2.0   0.0   0.0   
10   0.0   0.0   0.0  -1.0   0.0  -1.0   0.0   0.0   0.0  -1.0   
11   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
12   1.0  -1.0   1.0   1.0  -1.0   1.0   0.0  -1.0   3.0   0.0   
13   1.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   1.0   
14   1.0   1.0   3.0   2.0   0.0   0.0   0.0   2.0   3.0   4.0   
15   1.0   7.0   4.0   4.0   0.0   1.0  -2.0   3.0   5.0   4.0   
16   1.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
17  -2.0   0.0  -2.0  -1.0  -1.0  -2.0   0.0   0.0   1.0  -1.0   
18  -1.0   0.0  -2.0   0.0   0.0   0.0   0.0   0.0  -2.0  -1.0   
19   1.0   0.0   0.0   0.0  -1.0   0.0   1.0   0.0   1.0   0.0   
20   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
21  -2.0   1.0  -1.0   3.0   1.0   0.0   3.0   0.0   2.0   3.0   
22   0.0   1.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0   
23   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   
24   0.0   0.0  -2.0  -1.0   0.0   0.0   0.0  -2.0   1.0   0.0   
25  -1.0  -1.0  -1.0   0.0   2.0  -1.0   0.0  -2.0   0.0   0.0   
26  -2.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  -2.0   

           COUNTRY  2008  
0          Germany     0  
1       Luxembourg     0  
2      Netherlands     0  
3            Italy     0  
4   United Kingdom     0  
5           France     0  
6          Austria     0  
7           Sweden     0  
8          Finland     0  
9           Cyprus     0  
10         Belgium     0  
11         Ireland     0  
12         Denmark     0  
13         Estonia     0  
14          Norway     0  
15  Czech Republic     0  
16          Latvia     0  
17          Poland     0  
18           Spain     0  
19        Slovakia     0  
20           Malta     0  
21         Romania     0  
22       Lithuania     0  
23         Croatia     0  
24         Hungary     0  
25        Bulgaria     0  
26     Switzerland     0

In [67]:
new_pops = []
for p in population:
    for i, arr in enumerate(p['starting_state']):
        for j, elem in enumerate(arr):
            if elem<0:
                p['starting_state'][i][j]=0
    p['error']=None
    new_pops.append(p)
print(len(new_pops))
pickle.dump(new_pops, open('./data/optimization/population_edge_3_11.xx.pickle','wb'))

70


## Crossing over

In [220]:
p1 = population[7]
p1

{'starting_state': [array([ 9, 47]),
  array([12, 34]),
  array([13, 18]),
  array([63,  2]),
  array([ 9, 48]),
  array([ 8, 38]),
  array([67,  2]),
  array([35, 28]),
  array([45, 48]),
  array([56,  9]),
  array([25, 12]),
  array([45, 60]),
  array([50, 20]),
  array([39, 64]),
  array([32, 42]),
  array([18, 18]),
  array([59,  0]),
  array([70, 12])],
 'strategies': [array([[0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0]]),
  array([[1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0]]),
  array([[1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0]]),
  array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0]]),
  array([[0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]]),
  array([[1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0]]),
  array([[1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1]]),
  array([[1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0]]),
  array([[1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0]]),
  array([[1, 0, 1, 0, 

In [211]:
p2 = population[10]

In [228]:
p2['strategies'][1][0][1]

1

In [3]:
from corpgame import PolymatrixGame
import numpy as np
import pickle

def in_list(candidate, full_list):
    for element in full_list:
        if candidate==element:
            return True
    return False


game_settings = {
        "start_populations_matrix": [[5, 10], [5, 5], [15, 5], [15, 5], [30, 5],[3,17]],
        "topology": "chain",
        'alpha': 0.7,
        'log_level': "warning"
    }
game = PolymatrixGame(**game_settings)
self = game.network
print(game.network.graph.edges)

keep_looking = True
n = len(self.graph.nodes)
m = len(self.graph.edges)
if m<n*(n-1)/2:
    edges = list(self.graph.edges)
    nodes = list(range(0,n))
    possible_edges = [
                    [nodes[i], nodes[j]]
                    for i in range(len(nodes))
                    for j in range(i + 1, len(nodes))
                ]
    temp_graph = self.graph.copy()
    while keep_looking and len(possible_edges)!=0: # try to remove edges but only if it doesn't disconnect the graph
        edge_candidate = tuple(possible_edges.pop(np.random.randint(0,len(possible_edges))))
        #print(edge_candidate, edges, in_list(edge_candidate, edges))
        if not in_list(edge_candidate, edges):
            temp_graph.add_edge(*edge_candidate)
            self.graph = temp_graph.copy()
            keep_looking=False
print(self.graph.edges)

[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)]
[(0, 1), (1, 2), (1, 5), (2, 3), (3, 4), (4, 5)]


In [39]:
print(game.network.graph.edges)

keep_looking = True
n = len(self.graph.nodes)
m = len(self.graph.edges)
if m<n*(n-1)/2:
    edges = list(self.graph.edges)
    nodes = list(range(0,n))
    possible_edges = [
                    [nodes[i], nodes[j]]
                    for i in range(len(nodes))
                    for j in range(i + 1, len(nodes))
                ]
    temp_graph = self.graph.copy()
    while keep_looking and len(possible_edges)!=0: # try to remove edges but only if it doesn't disconnect the graph
        edge_candidate = tuple(possible_edges.pop(np.random.randint(0,len(possible_edges))))
        #print(edge_candidate, edges, in_list(edge_candidate, edges))
        if not in_list(edge_candidate, edges):
            temp_graph.add_edge(*edge_candidate)
            self.graph = temp_graph.copy()
            keep_looking=False
print(self.graph.edges)

[(0, 1), (0, 2), (0, 3), (0, 5), (0, 4), (1, 2), (1, 5), (1, 3), (1, 4), (2, 3), (2, 5), (2, 4), (3, 4), (3, 5), (4, 5)]
[(0, 1), (0, 2), (0, 3), (0, 5), (0, 4), (1, 2), (1, 5), (1, 3), (1, 4), (2, 3), (2, 5), (2, 4), (3, 4), (3, 5), (4, 5)]


In [41]:
n = 18
nodes = list(range(n))

edges = [
            [nodes[i], nodes[j]]
            for i in range(len(nodes))
            for j in range(i + 1, len(nodes))
        ]

edges = list(np.random.permutation(list(edges)))
edges

[array([3, 7]),
 array([ 8, 14]),
 array([7, 8]),
 array([ 3, 12]),
 array([11, 17]),
 array([ 9, 14]),
 array([0, 1]),
 array([ 7, 10]),
 array([10, 14]),
 array([12, 15]),
 array([ 3, 10]),
 array([ 2, 14]),
 array([ 1, 11]),
 array([1, 5]),
 array([ 0, 10]),
 array([10, 13]),
 array([ 5, 16]),
 array([5, 6]),
 array([1, 9]),
 array([5, 8]),
 array([5, 9]),
 array([12, 16]),
 array([1, 2]),
 array([4, 9]),
 array([11, 15]),
 array([10, 12]),
 array([4, 7]),
 array([2, 9]),
 array([ 9, 16]),
 array([2, 8]),
 array([2, 4]),
 array([3, 9]),
 array([ 7, 14]),
 array([8, 9]),
 array([ 2, 17]),
 array([0, 5]),
 array([1, 4]),
 array([ 1, 16]),
 array([ 4, 11]),
 array([ 0, 11]),
 array([0, 3]),
 array([ 6, 15]),
 array([ 1, 13]),
 array([ 2, 12]),
 array([ 0, 13]),
 array([1, 8]),
 array([ 6, 10]),
 array([15, 16]),
 array([4, 6]),
 array([3, 6]),
 array([7, 9]),
 array([1, 6]),
 array([0, 2]),
 array([ 2, 16]),
 array([ 1, 17]),
 array([0, 9]),
 array([2, 7]),
 array([ 2, 11]),
 array([6,

In [ ]:
if np.random.randint==
if len(game.network.graph.edges)>(len(game.players)-1):
    game.network.remove_random_edge()
    hypothesis['topology'] = list(game.network.graph.edges)
return hypothesis