Checking best strategies in the last round

In [22]:
import pickle
from corpgame import PolymatrixGame
from genetic import *
import numpy as np
from sklearn.metrics import mean_squared_error
population = pickle.load(open('./data/optimization/population_edgeval_1.499.pickle','rb'))
p = population[0]
p

{'starting_state': [array([37844, 46141]),
  array([ 184, 4485]),
  array([  8658, 129144]),
  array([77510, 26887]),
  array([183701,  51624]),
  array([20836, 34014]),
  array([5554, 8694]),
  array([6734, 4386]),
  array([3486, 3057]),
  array([565, 577]),
  array([ 3315, 11526]),
  array([1407, 1670]),
  array([1923, 2808]),
  array([ 321, 3003]),
  array([ 2551, 16347]),
  array([ 1773, 31682]),
  array([ 852, 1465]),
  array([18211, 14883]),
  array([16974, 28076]),
  array([9678, 1339]),
  array([5049,  221]),
  array([  143, 11666]),
  array([4992, 2479]),
  array([2452,  621]),
  array([ 1360, 29419]),
  array([12375,   343]),
  array([35764,  4592])],
 'strategies': [array([[1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
          1, 0, 1, 1, 1]]),
  array([[1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
          0, 0, 1, 1, 0]]),
  array([[1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
          0, 1, 0, 1, 0]]),
  ar

In [25]:
hypothesis = population[0]
game_settings = {
            "start_populations_matrix": hypothesis['starting_state'],
            "topology": hypothesis['topology'],
            'alpha': hypothesis['alpha'],
            'log_level': "warning",
            'player_labels':hypothesis['player_labels']
        }
game = PolymatrixGame(**game_settings)
game.get_all_payoffs()

MemoryError: 

In [29]:
for i in range(28):
    print(i, 2**i)

0 1
1 2
2 4
3 8
4 16
5 32
6 64
7 128
8 256
9 512
10 1024
11 2048
12 4096
13 8192
14 16384
15 32768
16 65536
17 131072
18 262144
19 524288
20 1048576
21 2097152
22 4194304
23 8388608
24 16777216
25 33554432
26 67108864
27 134217728


Solving and intervention

In [49]:
for i in range(100):
    k=8
    game_settings = {
                "start_populations_matrix": list(np.random.randint(0, 500, (k,2))),
                "topology": list(nx.erdos_renyi_graph(k, np.random.rand(1)).edges),
                'alpha': 1,
                'log_level': "warning",
                'player_labels':p['player_labels'][0:k]
            }
    game = PolymatrixGame(**game_settings)
    game.solve()
    print(i, len(game.network.edges), len(game.pne))

0 7 2
1 21 1
2 0 256
3 21 0
4 19 0
5 19 0
6 12 1
7 5 4
8 0 256
9 22 0
10 28 0
11 2 0
12 13 0
13 19 1
14 21 0
15 11 1
16 23 1
17 25 0
18 25 1
19 2 0
20 18 0
21 8 1
22 19 0
23 4 8
24 3 0
25 7 0
26 14 1
27 13 1
28 8 0
29 22 0
30 4 4
31 11 1
32 26 0
33 5 0
34 11 0
35 3 0
36 11 0
37 17 0
38 10 1
39 23 1
40 22 1
41 19 0
42 21 1
43 7 0
44 14 1
45 28 1
46 25 1
47 28 1
48 26 0
49 22 0
50 6 0
51 18 0
52 2 32
53 0 256
54 26 0
55 20 1
56 4 0
57 22 1
58 6 2
59 12 0
60 26 1
61 16 0
62 26 1
63 19 0
64 18 1
65 1 0
66 0 256
67 21 0
68 25 0
69 22 1
70 10 0
71 6 0
72 22 1
73 5 0
74 15 0
75 5 0
76 2 16
77 2 0
78 5 0
79 11 2
80 25 0
81 21 0
82 25 0
83 19 0
84 23 0
85 15 1
86 0 256
87 15 0
88 27 0
89 23 1
90 4 0
91 4 0
92 18 0
93 14 0
94 27 1
95 24 0
96 11 1
97 25 1
98 0 256
99 12 0


1

In [15]:
k=5
np.random.randint(0, 500, (k,2))

array([[338, 420],
       [ 13,  62],
       [236, 497],
       [224, 294],
       [406, 101]])

In [31]:
list(nx.erdos_renyi_graph(n, np.random.rand(1)).edges)

[(0, 1),
 (0, 4),
 (0, 6),
 (0, 8),
 (0, 12),
 (0, 13),
 (0, 19),
 (0, 20),
 (0, 21),
 (1, 3),
 (1, 4),
 (1, 6),
 (1, 7),
 (1, 8),
 (1, 10),
 (1, 15),
 (1, 16),
 (1, 19),
 (1, 22),
 (1, 24),
 (1, 26),
 (2, 20),
 (2, 22),
 (2, 25),
 (3, 6),
 (3, 10),
 (3, 11),
 (3, 13),
 (3, 16),
 (3, 19),
 (3, 21),
 (3, 22),
 (3, 24),
 (3, 26),
 (4, 5),
 (4, 6),
 (4, 13),
 (4, 16),
 (4, 17),
 (4, 18),
 (4, 23),
 (4, 25),
 (5, 7),
 (5, 10),
 (5, 11),
 (5, 16),
 (5, 17),
 (5, 21),
 (5, 23),
 (5, 25),
 (5, 26),
 (6, 8),
 (6, 11),
 (6, 13),
 (6, 15),
 (6, 16),
 (6, 17),
 (6, 18),
 (6, 20),
 (6, 21),
 (6, 25),
 (6, 26),
 (7, 8),
 (7, 10),
 (7, 14),
 (7, 16),
 (7, 17),
 (7, 20),
 (7, 21),
 (7, 23),
 (7, 25),
 (7, 26),
 (8, 9),
 (8, 12),
 (8, 13),
 (8, 17),
 (8, 18),
 (8, 19),
 (8, 20),
 (9, 15),
 (9, 16),
 (9, 18),
 (9, 19),
 (9, 20),
 (9, 22),
 (9, 23),
 (9, 24),
 (9, 25),
 (9, 26),
 (10, 11),
 (10, 13),
 (10, 14),
 (10, 15),
 (10, 20),
 (10, 23),
 (10, 25),
 (11, 12),
 (11, 13),
 (11, 15),
 (11, 18),
 (11,