In [63]:
import numpy as np
x = np.array([[1/2,1/2,0]]).transpose() #colgril
y = np.array([[1/3,2/3,0]]) #rowboy
a = np.array([[0,1,-1],[-1, 0 ,1],[1,-1,0]])

In [64]:
y@a@x

array([[-0.16666667]])

In [65]:
x.transpose()@a@y.transpose()

array([[0.16666667]])

In [40]:
a

array([[ 0,  1, -1],
       [-1,  0,  1],
       [ 1, -1,  0]])

In [54]:
y@a@x

array([[0.]])

In [51]:
c = [-1, 4]
A = [[-3, 1], [1, 2]]
b = [6, 4]
x0_bounds = (None, None)
x1_bounds = (-3, None)
from scipy.optimize import linprog
res = linprog(c, A_ub=A, b_ub=b, bounds=[x0_bounds, x1_bounds])

In [53]:
print(res)

     con: array([], dtype=float64)
     fun: -21.999999840824938
 message: 'Optimization terminated successfully.'
     nit: 6
   slack: array([3.89999997e+01, 8.46872492e-08])
  status: 0
 success: True
       x: array([ 9.99999989, -2.99999999])


In [66]:
750*50

37500